language: csharp
dist: xenial
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
    - master
    - /^release\/.*$/
    - develop
dotnet: 5.0
jdk: openjdk11

#mono: none
os:
  - linux
before_install:
  - sudo apt-get install dotnet-sdk-2.1.4
  - sudo apt-get install dotnet-sdk-2.2
script:
  - set -e
  - dotnet tool install --global Cake.Tool --version 0.37.0
  - dotnet tool install --global coverlet.console --version 1.7.1
  - dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8
  - dotnet tool install --global coveralls.net --version 1.0.0
  - dotnet tool install --global GitVersion.Tool --version 5.3.4
  - dotnet tool install --global dotnet-sonarscanner --version 4.8.0
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - git fetch --unshallow
  - ./build.sh

