language: csharp
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
    - develop
    - master
    - main
    - support
    - /^release\/.*$/
    - /^feature\/.*$/
    - /^hotfix\/.*$/

dotnet: 6.0
jdk: openjdk11
git:
   depth: false
os:
  - linux
script:
  - set -e
  - dotnet tool install --global Cake.Tool --version 2.3.0
  - dotnet tool install --global coverlet.console --version 3.2.0
  - dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.10
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet-cake

