language: csharp
#dist: xenial
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
    - master
    - /^release\/.*$/
    - develop
dotnet: 6.0
jdk: openjdk11

#mono: none
os:
  - linux
#before_install:
#  - sudo apt-get install dotnet-sdk-2.1.4
#  - sudo apt-get install dotnet-sdk-2.2
script:
  - set -e
  - dotnet tool install --global Cake.Tool --version 2.3.0
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - git fetch --unshallow
  - ./build.sh

