# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - main
  - develop
  - release/*
  - feature/*
  - hotfix/*
  - bugfix/*
  - support

variables:
  - group: rsql4net.vars


pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |-
      dotnet tool install --global coverlet.console --version 3.2.0 && \
      dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.10

- task: Cake@2
  inputs:
    script: 'build.cake'
    target: 'Package'
    verbosity: 'Verbose'

- task: reportgenerator@5
  inputs:
    reports: 'coverage-results/merge-coverage.json'
    targetdir: 'coveragereport'
    sourcedirs: 'src/'
