# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - main
  - develop
  - release/*
  - feature/*
  - hotfix/*
  - bugfix/*
  - support

variables:
  - group: rsql4net.vars


pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Dotnet tools install components'
  inputs:
    targetType: 'inline'
    script: |-
      dotnet tool install --global coverlet.console --version 3.2.0 && \
      dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.10

- task: Cake@2
  displayName: 'Cake execute script'
  inputs:
    script: build.cake
    target: Package
    verbosity: Verbose
  env:
    SONAR_CLOUD_LOGIN: $(SonarCloud.Login)

- task: reportgenerator@5
  inputs:
    reports: '$(System.DefaultWorkingDirectory)/coverage-results/coverage.xml'
    targetdir: 'coveragereport'
    sourcedirs: '$(System.DefaultWorkingDirectory)/src/'
